image: registry.gitlab.com/matteobachetti/heasarc_pipelines:latest

test:3.5:
  stage: test
  script:
    - source activate py35
    - python setup.py test --coverage
    - coverage report -m --rcfile=heasarc_pipelines/tests/coveragerc

test:3.4:
  stage: test
  script:
    - source activate py34
    - python setup.py test --coverage
    - coverage report -m --rcfile=heasarc_pipelines/tests/coveragerc

test:2.7:
  stage: test
  script:
    - source activate py27
    - python setup.py test --coverage
    - coverage report -m --rcfile=heasarc_pipelines/tests/coveragerc