[tox]
envlist =
    py{312,313}-test{,-alldeps,-devdeps}{,-cov}
    py312-test-oldestdeps
    build_docs
    linkcheck
    codestyle
requires =
    tox >= 4
    tox-uv >= 1.0
isolated_build = true

[testenv]
# Suppress display of matplotlib plots generated during docs build
setenv =
    MPLBACKEND=agg
    # Nightly wheels of the scientific Python stack
    devdeps: UV_PRERELEASE=allow
    devdeps: UV_EXTRA_INDEX_URL=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
    devdeps: UV_INDEX_STRATEGY=unsafe-best-match

# Pass through the following environment variables which may be needed for the CI
passenv = HOME,WINDIR,LC_ALL,LC_CTYPE,CC,CI

# Run the tests in a temporary directory to make sure that we don't import
# this package from the source tree
changedir = .tmp/{envname}

# tox environments are constructed with so-called 'factors' (or terms)
# separated by hyphens, e.g. test-devdeps-cov. Lines below starting with factor:
# will only take effect if that factor is included in the environment name. To
# see a list of example environments that can be run, along with a description,
# run:
#
#     tox -l -v
#
description =
    run tests
    alldeps: with all optional dependencies
    devdeps: with the latest developer version of key dependencies
    oldestdeps: with the oldest supported version of all direct dependencies
    cov: and test coverage

# The oldest versions are those given as lower bounds in pyproject.toml
uv_resolution =
    oldestdeps: lowest-direct

deps =
    cov: coverage
    devdeps: numpy>=0.0.dev0
    devdeps: scipy>=0.0.dev0
    devdeps: matplotlib>=0.0.dev0
    devdeps: astropy>=0.0.dev0

# The following indicates which extras_require from pyproject.toml will be installed
extras =
    test
    alldeps: all

commands =
    uv pip freeze
    !cov: pytest --pyargs srttools {posargs}
    cov: pytest --pyargs srttools --cov srttools --cov-config={toxinidir}/pyproject.toml {posargs}
    cov: coverage xml --rcfile={toxinidir}/pyproject.toml -o {toxinidir}/coverage.xml

allowlist_externals = uv

[testenv:build_docs]
changedir = docs
description = invoke sphinx-build to build the HTML docs
extras = docs
commands =
    uv pip freeze
    sphinx-build -W -b html . _build/html

[testenv:linkcheck]
changedir = docs
description = check the links in the HTML docs
extras = docs
commands =
    uv pip freeze
    sphinx-build -W -b linkcheck . _build/html

[testenv:codestyle]
skip_install = true
changedir = {toxinidir}
description = Run all style and file checks with pre-commit
deps =
    pre-commit
commands =
    pre-commit install-hooks
    pre-commit run {posargs:--color always --all-files --show-diff-on-failure}
